general:
  buildTool: "mta"
  verbose: true

steps:
  mtaBuild:
    platform: "CF"
    artifactPrepareVersion:
      versioningType: "cloud_noTag"

  cloudFoundryDeploy:
    deployTool: "mtaDeployPlugin"
    deployType: "standard"
    cloudFoundry:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "Next-Wave-Free-Tier"
      space: "dev"
      credentialsId: "cf-credentials"
    verbose: true