steps:
  mtaBuild:
    platform: "CF"
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "Next-Wave-Free-Tier"
      space: "dev"
      credentialsId: "cf-credentials"
    verbose: true