stages:
  Init:
    steps:
      - setupCommonPipelineEnvironment
  NPM Build:
    steps:
      - npmExecuteScripts
  MTA Build:
    steps:
      - mtaBuild
  Deploy to Cloud Foundry:
    steps:
      - cloudFoundryDeploy